name: wrench
version: 0.0.2.7
github: "ryukzak/wrench"
license: BSD-3-Clause
author: "Aleksandr Penskoi"
maintainer: "aleksandr.penskoi@gmail.com"
copyright: "2025 Aleksandr Penskoi"

extra-source-files:
  - README.md

description: Wrench - is a tool for educating computer architecture.

default-extensions:
  - AllowAmbiguousTypes
  - ConstraintKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - ImportQualifiedPost
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - RankNTypes
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

dependencies:
  - aeson
  - aeson-casing
  - base >= 4.7 && < 5
  - data-default
  - filepath
  - gitrev
  - megaparsec
  - mtl
  - optparse-applicative
  - pretty-simple
  - regex-tdfa
  - relude
  - split
  - th-env
  - yaml

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  wrench:
    main: Main.hs
    other-modules: []
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wrench

  wrench-serv:
    main: WrenchServ.hs
    other-modules: []
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base64
      - cookie
      - cryptohash-sha1
      - crypton
      - directory
      - http-api-data
      - http-conduit
      - lucid
      - network-uri
      - process
      - servant
      - servant-lucid
      - servant-server
      - text
      - time
      - uuid
      - vector
      - wai
      - wai-extra
      - warp
      - wrench

  wrench-fmt:
    main: Fmt.hs
    other-modules: []
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory
      - http-api-data
      - lucid
      - network-uri
      - process
      - servant
      - servant-lucid
      - servant-server
      - text
      - time
      - uuid
      - wai
      - wai-extra
      - warp
      - wrench

tests:
  wrench-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tasty
      - tasty-golden
      - tasty-hunit
      - tasty-rerun
      - wrench
